version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    volumes: 
      - ./DataBase.sql:/docker-entrypoint-initdb.d/DataBase.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_lend
    ports:
      - "3308:3306"

  admin:    
    image: adminer    
    ports:      
      - "8080:8080"

  lending-service:    
    image: lucasgreck/lending-service
    ports:      
      - "8089:8080"
    environment: 
      - MYSQL_DB_HOST=jdbc:mysql://mysql-development:3306/books_lend?serverTimezone=UTC
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=root
    restart: on-failure 