# Configuration de logging pour Kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: library-system
  labels:
    app: lending-service
    component: logging
data:
  django_logging.conf: |
    [loggers]
    keys=root,lending,django

    [handlers]
    keys=console,file,json

    [formatters]
    keys=verbose,simple,json

    [logger_root]
    level=WARNING
    handlers=console

    [logger_lending]
    level=INFO
    handlers=console,json
    qualname=lending
    propagate=0

    [logger_django]
    level=INFO
    handlers=console
    qualname=django
    propagate=0

    [handler_console]
    class=StreamHandler
    level=INFO
    formatter=json
    args=(sys.stdout,)

    [handler_file]
    class=handlers.RotatingFileHandler
    level=INFO
    formatter=verbose
    args=('/app/logs/lending-service.log', 'a', 10485760, 5)

    [handler_json]
    class=StreamHandler
    level=INFO
    formatter=json
    args=(sys.stdout,)

    [formatter_verbose]
    format=%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s

    [formatter_simple]
    format=%(levelname)s %(message)s

    [formatter_json]
    format={"timestamp": "%(asctime)s", "level": "%(levelname)s", "service": "lending-management", "module": "%(module)s", "message": "%(message)s", "process": %(process)d, "thread": %(thread)d}