apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lending-service-pvc
  namespace: library-system
  labels:
    app: lending-service
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adapter selon votre cluster