# Generated by Django 5.2.6 on 2025-09-19 09:55

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_alter_lending_date_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lending",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RETURNED", "Returned"),
                    ("OVERDUE", "Overdue"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lending",
            name="date_due",
            field=models.DateTimeField(default=lending.models.two_months_from_now),
        ),
        migrations.AlterUniqueTogether(
            name="lending",
            unique_together={("user_email", "book_id", "status")},
        ),
        migrations.AddIndex(
            model_name="lending",
            index=models.Index(fields=["status"], name="lending_len_status_9cf3f7_idx"),
        ),
        migrations.AddIndex(
            model_name="lending",
            index=models.Index(
                fields=["date_due"], name="lending_len_date_du_8a0519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lending",
            index=models.Index(
                fields=["user_email"], name="lending_len_user_em_ce0f12_idx"
            ),
        ),
    ]
