name: Build docker image

on:
  push:
    branches:
    - master, features/guillval, Teddy, feature/yanis_side
  pull_request:

jobs:
  
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        registry: docker.io
        repository: lucasgreck/lending-service
        tag_with_sha: true
